version: '3.8'

services:
  db:
    image: mysql:8.4
    container_name: mysql8-envtracker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: envtracker
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: flask_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db:3306
      MASTER_USER: root
      MASTER_PASSWORD: root
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  db_data: